apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        aadpodidbinding: inventory
    spec:
      containers:
        - name: inventory
          image: dotnetplayeconomy.azurecr.io/play.inventory:1.0.5
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: dotnetplayeconomy
            - name: ServiceSettings__Authority
              value: https://dotnetplayeconomy.eastus.cloudapp.azure.com/inventory-svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5004
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5004
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5004
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - port: 80
      targetPort: 5004
